name: e2e

on:
  push:
  pull_request:
  workflow_dispatch:
  #schedule:
    # 11:40 AM CST (UTC-6) = 17:40 UTC
    # cron: "40 17 * * *"   --> runs at 17 40 which is 11.40 CTC
    # "*/5 * * * *"  every 5 mins
    #- cron: "*/30 * * * *"

jobs:
  cucumber-playwright:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Cucumber tests (headless)
        run: npm test
        env:
          # Optional: provide base url to the worldParameters via env + CLI if you want
          # BASE_URL: "https://example.com"
          CI: "true"
